services:
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:3000:3000"  # Map backend port to host
    networks:
      - my-network
    volumes: 
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3001:3001"  # Map frontend port to host
    depends_on:
      - backend  # Ensure backend starts before frontend
    networks:
      - my-network
    volumes:
      - ./frontend:/app
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=farid
      - POSTGRES_PASSWORD=fjfj
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      # - "3123:3123"
      - "127.0.0.1:5433:5432"
    volumes:
      - ./backend/db:/var/lib/postgresql/data
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

  redis:
    image: redis:latest
networks:
  my-network:
    driver: bridge