services:
  # backend:
  # frontend:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=farid
      - POSTGRES_PASSWORD=fjfj
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      # - "3123:3123"
      - "127.0.0.1:5433:5432"
    volumes:
      - ./backend/db:/var/lib/postgresql/data
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest